// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: V0

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Available
void ui_Available_screen_init(void);
void ui_event_Available(lv_event_t * e);
void msgbox_event_cb(lv_event_t * e);
lv_obj_t * ui_Available;
lv_obj_t * ui_Image10;
lv_obj_t * ui_NextMeet;


// SCREEN: ui_busy
void ui_busy_screen_init(void);
lv_obj_t * ui_busy;
lv_obj_t * ui_Image11;
lv_obj_t * ui_NextMeet2;


// SCREEN: ui_menu
void ui_menu_screen_init(void);
lv_obj_t * ui_menu;
lv_obj_t * ui_Image12;
void ui_event_menu_Roller1(lv_event_t * e);
lv_obj_t * ui_menu_Roller1;


// SCREEN: ui_timer
void ui_timer_screen_init(void);
lv_obj_t * ui_timer;
lv_obj_t * ui_Image13;
lv_obj_t * ui_timer_Label1;
void ui_event_timer_Arc1(lv_event_t * e);
lv_obj_t * ui_timer_Arc1;


// SCREEN: ui_Vcode
void ui_Vcode_screen_init(void);
lv_obj_t * ui_Vcode;
lv_obj_t * ui_Image14;
lv_obj_t * ui_NextMeet3;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Available(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_menu_screen_init);
    }
}
void msgbox_event_cb(lv_event_t * e)
{
    lv_obj_t * msgbox = lv_event_get_user_data(e);
    lv_msgbox_close(msgbox);
    lv_group_focus_freeze(lv_group_create(), false);
    lv_group_focus_obj(lv_obj_get_child(ui_Available, 0));
    lv_obj_scroll_to(ui_Available, 0, 0, LV_ANIM_OFF);
}
void ui_event_menu_Roller1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        _ui_roller_set_property(ui_menu_Roller1, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 1);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        _ui_roller_set_property(ui_menu_Roller1, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 0);
    }
    if(event_code == LV_EVENT_KEY) {
        _ui_screen_change(&ui_Vcode, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Vcode_screen_init);
    }
}
void ui_event_timer_Arc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_timer_Label1, target, "00:", "");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Available_screen_init();
    ui_busy_screen_init();
    ui_menu_screen_init();
    ui_timer_screen_init();
    ui_Vcode_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Available);
}
