// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: V0

#ifndef _V0_UI_H
#define _V0_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Available
void ui_Available_screen_init(void);
void ui_event_Available(lv_event_t * e);
void msgbox_event_cb(lv_event_t * e);
extern lv_obj_t * ui_Available;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_NextMeet;
// SCREEN: ui_busy
void ui_busy_screen_init(void);
extern lv_obj_t * ui_busy;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_NextMeet2;
// SCREEN: ui_menu
void ui_menu_screen_init(void);
extern lv_obj_t * ui_menu;
extern lv_obj_t * ui_Image12;
void ui_event_menu_Roller1(lv_event_t * e);
extern lv_obj_t * ui_menu_Roller1;
// SCREEN: ui_timer
void ui_timer_screen_init(void);
extern lv_obj_t * ui_timer;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_timer_Label1;
void ui_event_timer_Arc1(lv_event_t * e);
extern lv_obj_t * ui_timer_Arc1;
// SCREEN: ui_Vcode
void ui_Vcode_screen_init(void);
extern lv_obj_t * ui_Vcode;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_NextMeet3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_available_png);    // assets/Available.png
LV_IMG_DECLARE(ui_img_busy_png);    // assets/BUSY.png
LV_IMG_DECLARE(ui_img_timer_menu_png);    // assets/timer_menu.png
LV_IMG_DECLARE(ui_img_enter_code_png);    // assets/enter_code.png


static void selectors_create(lv_obj_t * parent);
static void text_input_create(lv_obj_t * parent);
static void msgbox_create(void);

static void ta_event_cb(lv_event_t * e);





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
