// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: V0

#include "ui.h"

void ui_busy_screen_init(void)
{
    ui_busy = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_busy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_image_create(ui_busy);
    lv_image_set_src(ui_Image11, &ui_img_busy_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 241
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 241
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextMeet2 = lv_textarea_create(ui_busy);
    lv_obj_set_width(ui_NextMeet2, 143);
    lv_obj_set_height(ui_NextMeet2, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_NextMeet2, -22);
    lv_obj_set_y(ui_NextMeet2, 68);
    lv_obj_set_align(ui_NextMeet2, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_NextMeet2, 6);
    lv_textarea_set_placeholder_text(ui_NextMeet2, "00:00h");
    lv_textarea_set_one_line(ui_NextMeet2, true);
    lv_obj_set_style_text_color(ui_NextMeet2, lv_color_hex(0x3D85C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NextMeet2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NextMeet2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NextMeet2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NextMeet2, lv_color_hex(0xDEF2C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NextMeet2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NextMeet2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NextMeet2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_NextMeet2, lv_color_hex(0x3D85C6), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NextMeet2, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NextMeet2, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NextMeet2, &lv_font_montserrat_32, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

}
