// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: V0

#include "ui.h"

void ui_menu_screen_init(void)
{
    ui_menu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_image_create(ui_menu);
    lv_image_set_src(ui_Image12, &ui_img_timer_menu_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menu_Roller1 = lv_roller_create(ui_menu);
    lv_roller_set_options(ui_menu_Roller1, "Right Now meet\nPlanned meet", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_menu_Roller1, 94);
    lv_obj_set_width(ui_menu_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_menu_Roller1, -31);
    lv_obj_set_y(ui_menu_Roller1, -13);
    lv_obj_set_align(ui_menu_Roller1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_menu_Roller1, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_menu_Roller1, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_remove_flag(ui_menu_Roller1, LV_OBJ_FLAG_PRESS_LOCK);      /// Flags
    lv_obj_set_style_text_color(ui_menu_Roller1, lv_color_hex(0x3D85C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menu_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menu_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menu_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menu_Roller1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menu_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_menu_Roller1, 100, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_menu_Roller1, ui_event_menu_Roller1, LV_EVENT_ALL, NULL);

}
