// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: V0

#include "ui.h"

void ui_timer_screen_init(void)
{
    ui_timer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_timer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_timer);
    lv_image_set_src(ui_Image13, &ui_img_timer_menu_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timer_Label1 = lv_label_create(ui_timer);
    lv_obj_set_width(ui_timer_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timer_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timer_Label1, -10);
    lv_obj_set_y(ui_timer_Label1, -2);
    lv_obj_set_align(ui_timer_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timer_Label1, "00:00");
    lv_obj_set_style_text_color(ui_timer_Label1, lv_color_hex(0x3D85C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timer_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timer_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timer_Arc1 = lv_arc_create(ui_timer);
    lv_obj_set_width(ui_timer_Arc1, 207);
    lv_obj_set_height(ui_timer_Arc1, 202);
    lv_obj_set_align(ui_timer_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_timer_Arc1, 0, 59);
    lv_arc_set_value(ui_timer_Arc1, 50);
    lv_arc_set_bg_angles(ui_timer_Arc1, 60, 320);


    lv_obj_add_event_cb(ui_timer_Arc1, ui_event_timer_Arc1, LV_EVENT_ALL, NULL);

}
