// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: V0

#include "ui.h"

void ui_Vcode_screen_init(void)
{
    ui_Vcode = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Vcode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_image_create(ui_Vcode);
    lv_image_set_src(ui_Image14, &ui_img_enter_code_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextMeet3 = lv_textarea_create(ui_Vcode);
    lv_obj_set_width(ui_NextMeet3, 189);
    lv_obj_set_height(ui_NextMeet3, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_NextMeet3, 1);
    lv_obj_set_y(ui_NextMeet3, -27);
    lv_obj_set_align(ui_NextMeet3, LV_ALIGN_CENTER);
    if("12345678" == "") lv_textarea_set_accepted_chars(ui_NextMeet3, NULL);
    else lv_textarea_set_accepted_chars(ui_NextMeet3, "12345678");
    lv_textarea_set_max_length(ui_NextMeet3, 6);
    lv_textarea_set_placeholder_text(ui_NextMeet3, "Code received by email.     ");
    lv_textarea_set_one_line(ui_NextMeet3, true);
    lv_textarea_set_password_mode(ui_NextMeet3, true);
    lv_obj_set_style_text_color(ui_NextMeet3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NextMeet3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NextMeet3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NextMeet3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NextMeet3, lv_color_hex(0xDEF2C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NextMeet3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NextMeet3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NextMeet3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_NextMeet3, lv_color_hex(0xFF0900), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NextMeet3, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NextMeet3, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_NextMeet3, LV_TEXT_DECOR_NONE, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NextMeet3, &lv_font_montserrat_14, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

}
